// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACfuBwIYlmngAXZNc_Kp6KmFdXjg9-yQ0',
    appId: '1:504767382186:web:8461a2c0d5982b8f7186d3',
    messagingSenderId: '504767382186',
    projectId: 'test-project-ea090',
    authDomain: 'test-project-ea090.firebaseapp.com',
    storageBucket: 'test-project-ea090.appspot.com',
    measurementId: 'G-QDRLW3TDN7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIIT4O3N8vIUo5_iqvJqYcmxSzu0mQwlc',
    appId: '1:504767382186:android:03f6a3895282f00a7186d3',
    messagingSenderId: '504767382186',
    projectId: 'test-project-ea090',
    storageBucket: 'test-project-ea090.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLTMFlngchnRGpyTk8YPV4w_p6DXCEtac',
    appId: '1:504767382186:ios:698b681e6218fada7186d3',
    messagingSenderId: '504767382186',
    projectId: 'test-project-ea090',
    storageBucket: 'test-project-ea090.appspot.com',
    iosClientId: '504767382186-4nc30sc0hj7flhtkp1lgito1hl2ir2nd.apps.googleusercontent.com',
    iosBundleId: 'com.example.satu',
  );
}
